apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: nestjs-k8s-debugging
build:
  artifacts:
    - image: nest-one
      context: nest-one
      docker:
        dockerfile: Dockerfile
        target: debug
    - image: nest-two
      context: nest-two
      docker:
        dockerfile: Dockerfile
        target: debug
manifests:
  rawYaml:
    - k8s/ingress.yaml
    - k8s/nest-one-deployment.yaml
    - k8s/nest-one-service.yaml
    - k8s/nest-two-deployment.yaml
    - k8s/nest-two-service.yaml